### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Vineversum/flexbox-template1#1]
какое-то странное мигание при наведении, так и должно быть?
![image](https://user-images.githubusercontent.com/8464662/61315867-60dfdf80-a808-11e9-91ba-d936b3d0e287.png)

синего контура быть не должно
![image](https://user-images.githubusercontent.com/8464662/61315903-78b76380-a808-11e9-91e5-cfe7747abd78.png)

**Comment by Vineversum** [comment]
Исправил. 
Мигание при наведении было тогда, когда они сдвигались при помощи свойств translateX и transition. Почему так работает мне пока понять не удалось. 
Вместо использования translateX теперь меняю значение  padding-left у родительского элемента. Достигается тот же эффект и мигания нет.

**Comment by Alecto** [comment]
![image](https://user-images.githubusercontent.com/8464662/61929977-26531100-af85-11e9-9469-14280c267b7e.png)

**Comment by Alecto** [comment]
![image](https://user-images.githubusercontent.com/8464662/61930131-8c3f9880-af85-11e9-85f3-1699a4a6c14a.png)

**Comment by Alecto** [comment]
![image](https://user-images.githubusercontent.com/8464662/62002905-128ae480-b116-11e9-804c-606e966e6c68.png)

кнопка меню при открытии увеличивает высоту блока..

**Comment by Vineversum** [comment]
Исправил

вс, 28 июл. 2019 г. в 09:01, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
принято

нд, 4 серп. 2019 о 19:37 Vineversum <notifications@github.com> пише:
